//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 北京工艺文件管理MVC.IFDBDatabase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class jdxa_file_info
    {
        [Key]
        public int FILE_ID { get; set; }
        public int FILE_TYPE { get; set; }
        public string FILE_NAME { get; set; }
        public decimal FILE_SIZE { get; set; }
        public string FILE_PROPERTY { get; set; }
        public string FILE_PATH { get; set; }
        public int FILE_DIRECTORY_ID { get; set; }
        public string FILE_NEW_NAME { get; set; }
        public short FLAG { get; set; }
        public string NOTE { get; set; }
        public int CREATE_USER_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public Nullable<int> UPDATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
    }
}
