//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 北京工艺文件管理MVC.IFDBDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JDXA_DNC_DB_JSEntities : DbContext
    {
        public JDXA_DNC_DB_JSEntities()
            : base("name=JDXA_DNC_DB_JSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<jdxa_file_info> jdxa_file_info { get; set; }
    }
}
